'Hay que hacer un diagrama de secuencia y clase para cada elemento del CRUD

@startuml 

'Ejemplo
'


actor cliente


cliente -> resource:  
resource -> service: 

service -> repositories: 
database BD
repositories -> BD:  
repositories <- BD:  
service <- repositories:  
resource <- service:  
cliente <- resource:  

@enduml

