'Hay que hacer un diagrama de secuencia y clase para cada elemento del CRUD

@startuml ver disponibilidad

'Ejemplo
'ver disponibilidad


actor cliente


cliente -> resource: blueprint departamentos desocupados
resource -> service: ver todos los disponibles

service -> repositories: traer departamentos disponibles
database BD
repositories -> BD: consulta
repositories <- BD: devuelve resultados de la consulta
service <- repositories: devuelve departamentos disponibles
resource <- service: devuelve departamentos disponibles
cliente <- resource: mostrar departamentos dispoibles

@enduml

