@startuml sistema-alquileres

class User {
    - name
    - lastname
    - phone_number
    - email_address
    - password
}

class Role {
    - name
    - description
}

class Booking {
    - start_booking
    - finish_booking
    - duration
    - amount_people
}

class Apartment {
    - number_of_apartment
    - size
    - amount_rooms
    - features
    - availability
    - lease
    - address
}

Booking -- User
Booking -- Apartment
User -- Role

@enduml